import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
const getId=(storage:Storage,key:string)=>{let id=storage.getItem(key);if(!id){id=crypto.randomUUID();storage.setItem(key,id);}return id;};
const device=()=>/Mobi|Android/i.test(navigator.userAgent)?'Celular':/Tablet|iPad/i.test(navigator.userAgent)?'Tablet':'Computador';
const browser=()=>/Edg\//.test(navigator.userAgent)?'Edge':/Chrome\//.test(navigator.userAgent)?'Chrome':/Firefox\//.test(navigator.userAgent)?'Firefox':/Safari\//.test(navigator.userAgent)?'Safari':'Outro';
const os=()=>/Windows/i.test(navigator.userAgent)?'Windows':/Android/i.test(navigator.userAgent)?'Android':/iPhone|iPad/i.test(navigator.userAgent)?'iOS':/Mac OS/i.test(navigator.userAgent)?'macOS':/Linux/i.test(navigator.userAgent)?'Linux':'Outro';
const send=(event:string,extra:Record<string,unknown>={})=>{try{const q=new URLSearchParams(location.search);const body=JSON.stringify({event,visitorId:getId(localStorage,'tr_assistant_visitor'),sessionId:getId(sessionStorage,'tr_site_session'),path:location.pathname,title:document.title,referrer:document.referrer||null,device:device(),browser:browser(),os:os(),utmSource:q.get('utm_source'),utmMedium:q.get('utm_medium'),utmCampaign:q.get('utm_campaign'),...extra});if(event==='page_exit'&&navigator.sendBeacon){navigator.sendBeacon('/api/analytics/site',new Blob([body],{type:'application/json'}));}else void fetch('/api/analytics/site',{method:'POST',headers:{'Content-Type':'application/json'},body,keepalive:true}).catch(()=>undefined);}catch{/* Analytics nunca interfere na navegação. */}};
const SiteAnalyticsTracker=()=>{const {pathname,search}=useLocation();useEffect(()=>{if(pathname.startsWith('/admin'))return;const started=Date.now();send('pageview');const seen=new Set<Element>();let observer:IntersectionObserver|undefined;const setup=window.setTimeout(()=>{observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting||seen.has(entry.target))return;seen.add(entry.target);const section=entry.target as HTMLElement;const heading=section.querySelector('h1,h2,h3')?.textContent?.trim();send('section_view',{label:section.id||heading||'Seção sem título'});}),{threshold:.45});document.querySelectorAll('main section').forEach(section=>observer?.observe(section));},400);const heartbeat=window.setInterval(()=>send('heartbeat'),60000);return()=>{clearTimeout(setup);observer?.disconnect();clearInterval(heartbeat);send('page_exit',{duration:Math.round((Date.now()-started)/1000)});};},[pathname,search]);useEffect(()=>{const click=(e:MouseEvent)=>{const a=(e.target as HTMLElement).closest('a');if(a)send('link_click',{label:(a.textContent||a.href).trim().slice(0,300)});};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true);},[]);return null;};
export default SiteAnalyticsTracker;
